#pragma once

#include "nmhook_common.h"

DECLARE_HOOKFUNC(EATCore);
DECLARE_HOOKFUNC(mcEventDetection);
DECLARE_HOOKFUNC(morphemeConnectCore);
DECLARE_HOOKFUNC(NMDatabase);
DECLARE_HOOKFUNC(NMDatabase2);
DECLARE_HOOKFUNC(NMDatabase2UI);
DECLARE_HOOKFUNC(NMDatabase2XMLIO);
DECLARE_HOOKFUNC(NMDatabaseUI);
DECLARE_HOOKFUNC(NMEditors);
DECLARE_HOOKFUNC(NMLua);
DECLARE_HOOKFUNC(NMLuaUI);
DECLARE_HOOKFUNC(NMUtils);
DECLARE_HOOKFUNC(NMWidgets);
DECLARE_HOOKFUNC(NMX2);
DECLARE_HOOKFUNC(NMX2Extensions);
DECLARE_HOOKFUNC(NMX2Foundation);
DECLARE_HOOKFUNC(NMX2PhysicsExtensions);
DECLARE_HOOKFUNC(NMX2UI);
DECLARE_HOOKFUNC(NMX2XMD);